name: Deploy to Staging Amazon ECS
on:
  push:
    branches:
      - staging

  workflow_run:
    workflows: ["Test Java Project"]
    types:
      - completed

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  ECR_REGION: us-east-1 # used for ECR Public login
  ECR_REPOSITORY: adpro-a07-staging/kilimanjaro
  REGISTRY_ALIAS: u3l0u1d1
  ECS_SERVICE: kilimanjaro-staging-service
  ECS_CLUSTER: adpro-a07-ecs-cluster
  ECS_TASK_DEFINITION: .aws/staging-task-definition.json
  CONTAINER_NAME: kilimanjaro-staging

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::000684258120:role/github-ecr-role
          aws-region: ${{ env.ECR_REGION }}

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR Public
        id: build-image
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$REGISTRY/$REGISTRY_ALIAS/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Re-configure AWS Credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_REGION: ap-southeast-1 # used for ECS deployment
        with:
          role-to-assume: arn:aws:iam::000684258120:role/github-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Re-configure AWS Credentials for ECS
        uses: aws-actions/configure-aws-credentials@v4
        env:
          AWS_REGION: ap-southeast-1 # used for ECS deployment
        with:
          role-to-assume: arn:aws:iam::000684258120:role/github-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.ECS_TASK_DEFINITION }}
          container-name: ${{ env.CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
